<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0-beta.1" />
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Stripe.net" Version="52.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Auth\Empresa\" />
    <Folder Include="Interfaces\Soporte\" />
  </ItemGroup>

</Project>
